### PR TITLE
fix: show 0% when there are no surplus apr items

### LINKED ISSUE #62: Show 0% LVR
When LVR is 0% show it in APR tooltip.

Image

### PR DESCRIPTION
**Pull request by groninge01**
fixes #62 

when there are no surplus apr items show LVR as 0% for cow amm pools

image

### CODE REVIEW

File: packages/lib/shared/components/tooltips/apr-tooltip/BaseAprTooltip.tsx [hunk 1]
```diff
@@ -185,12 +187,12 @@ function BaseAprTooltip({
...
         />
       )}
-      {hasSurplusIncentives && (
+      {isCowAmmPool(poolType) && (
         <TooltipAprItem
           {...basePopoverAprItemProps}
           displayValueFormatter={usedDisplayValueFormatter}
           title="Prevented LVR"
-          apr={surplusIncentivesAprDisplayed}
+          apr={hasSurplusIncentives ? surplusIncentivesAprDisplayed : bn(0)}
```
Comment (garethfuller) [inline packages/lib/shared/components/tooltips/apr-tooltip/BaseAprTooltip.tsx:195]: Do we need `hasSurplusIncentives` here? I think `surplusIncentivesAprDisplayed` will just be zero right?

Comment (groninge01) [reply packages/lib/shared/components/tooltips/apr-tooltip/BaseAprTooltip.tsx]: You're right. Removed it.

**Review by garethfuller — APPROVED** [review]
