### PR TITLE
fix: react-hooks-preserve-manual-memoization part 3

### LINKED ISSUE #1810: eslint rules react-hooks: preserve-manual-memoization

### PR DESCRIPTION
**Pull request by groninge01**
fixes #1810 

final fixes for `react-hooks-preserve-manual-memoization`

### CODE REVIEW

File: packages/lib/modules/transactions/transaction-steps/useSignRelayerStep.tsx [hunk 1]
```diff
@@ -15,44 +14,65 @@ import { LabelWithIcon } from '@repo/lib/shared/components/btns/button-group/Lab
...
-          >
-            <LabelWithIcon icon="sign">{buttonLabel}</LabelWithIcon>
-          </Button>
-        )}
-      </VStack>
-    )
-  }
-
-  const isComplete = () => signRelayerState === SignatureState.Completed
+  const isComplete = useCallback(
```
Comment (agorer) [inline packages/lib/modules/transactions/transaction-steps/useSignRelayerStep.tsx]: why do we need to add a new `useCallback` here?

**Review by MattPereira — APPROVED** [review]
