### PR TITLE
[#783] veBAL: Expired veBAL error

### LINKED ISSUE #783: veBAL: Expired veBAL error
Bug report:
- When the user's lock for their 'B-80BAL-20WETH' has expired, they should not have any veBAL. 
- Currently, the display shows small amounts like `<0.0001`

Image

Image

Task:
- Fix the display so that the user has zero veBAL when their lock has expired. 
- This is most likely an API error, so it may be best to coordinate with Franz to see why the API is returning the error. 
- This error is also displayed on the Vote page within the 'My veBAL' chip (pictured above).
- The display should look per the designs below:

Design:
- https://www.figma.com/design/Jrm12lbqVzLh1F46nWjdoK/zen-veBAL?node-id=1120-5988&t=DnRswGpo8MmX6Ket-1

Expired wallet to impersonate to see and test this issue:
- 0x6C8F61d3043f639F3404910A632cE0eA154b51d2

### PR DESCRIPTION
**Pull request by agorer**
Closes #783

### CODE REVIEW

File: packages/lib/modules/vebal/useVebalUserData.ts [hunk 1]
```diff
@@ -24,7 +24,7 @@ export function useVebalUserData() {
   return {
     data,
     refetch,
-    isConnected,
+    isConnected, // FIXME: [JUANJO] we shouldn't return account data from here
```
Comment (agualis) [inline packages/lib/modules/vebal/useVebalUserData.ts:27]: Can you fix it already in this PR?

**Review by agualis — CHANGES_REQUESTED** [review]

File: packages/lib/modules/vebal/useVebalUserData.ts (hunk 1 above)
Comment (agorer) [reply packages/lib/modules/vebal/useVebalUserData.ts:27]: I thought it was used in multiple places, but seems like isConnected is only used once. Will change it here.

**Review by agualis — APPROVED** [review]
