### PR TITLE
[LBP] several fixes

### LINKED ISSUE #1328: [LBP] missing token info when getting funds out
Image

### LINKED ISSUE #1330: [LBP] when moving between steps scroll to top of new step
tbd

### PR DESCRIPTION
**Pull request by groninge01**
fixes #1328 add missing token info (when getting funds out)
fixes #1330 add scroll to top on step change

### CODE REVIEW

File: packages/lib/modules/lbp/steps/SaleStructureStep.tsx [hunk 1]
```diff
@@ -181,14 +181,16 @@ export function SaleStructureStep() {
...
               </Text>
-              <Alert status={saleStartsSoon ? 'warning' : 'info'} variant="WideOnDesktop">
-                <AlertIcon as={saleStartsSoon ? AlertTriangle : LightbulbIcon} />
-                <AlertDescription>
-                  {saleStartsSoon && 'This sale is scheduled to start soon. '}
-                  {`The LBP will fail to launch unless you seed the initial liquidity before the
-                  scheduled start time at ${format(parseISO(saleStructureData.startTime), 'h:mmaaa, d MMMM yyyy')}.`}
-                </AlertDescription>
-              </Alert>
+              {saleStart && (
```
Comment (agorer) [inline packages/lib/modules/lbp/steps/SaleStructureStep.tsx:184]: I think this was already addressed by Matt at https://github.com/balancer/frontend-monorepo/pull/1321

File: packages/lib/modules/tokens/TokenRow/TokenRow.tsx [hunk 2]
```diff
@@ -188,7 +188,7 @@ export default function TokenRow({
       if (customUsdPrice) {
         setUsdValue(bn(customUsdPrice).times(value).toString())
       } else if ((isBpt || isNestedBpt) && pool) {
-        setUsdValue(usdValueForBpt(address, chain, value))
+        setUsdValue(usdValueForAddress(address, chain, value))
```
Comment (agorer) [inline packages/lib/modules/tokens/TokenRow/TokenRow.tsx:191]: Is this only for BPT's or will it work for any address? what does the address refer to here?

**Review by agorer — APPROVED** [review]

File: packages/lib/modules/tokens/TokenRow/TokenRow.tsx (hunk 2 above)
Comment (groninge01) [reply packages/lib/modules/tokens/TokenRow/TokenRow.tsx:191]: it will work for any token address, i will rename

File: packages/lib/modules/lbp/steps/SaleStructureStep.tsx (hunk 1 above)
Comment (groninge01) [reply packages/lib/modules/lbp/steps/SaleStructureStep.tsx:184]: ah i thought that was another issue, will update this PR
