### PR TITLE
[#785] get veBAL balance onchain instead of from API

### LINKED ISSUE #785: veBAL: New veBAL is taking several minutes to register
Bug report:

After locking tokens on a fresh account, and getting veBAL for the first time, it takes several minutes for the system to update for the user's new veBAL. For example, this warning is incorrectly displayed to the user, stating that they have no veBAL (even after a few minutes). This could be quite concerning for users until the update is registered by the system. 

Image

Note: The system has registered that the user has some veBAL, because the first warning mentions that the user's veBAL will expire soon. However, that is not reflected in the 'My veBAL' balance in the chip and with the displayed 2nd warning. So, there seems to be a timing mismatch from when the system first recognizes veBAL to when it is finally displayed.

To reproduce:
- Lock the ve8020 LP token to get veBAL on a new wallet that hasn't had any veBAL before
- See how long it takes for the veBAL on the user's UI to update.

### PR DESCRIPTION
**Pull request by agorer**
Closes #785

### CODE REVIEW

File: packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotes.tsx [hunk 1]
```diff
@@ -38,7 +39,10 @@ export function MyVotes() {
   const { isOpen, onOpen, onClose } = useDisclosure()
   const { isConnected } = useUserAccount()
 
-  const { loading: vebalUserDataLoading, myVebalBalance, noVeBalBalance } = useVebalUserData()
+  const { isLoading: vebalUserDataLoading, veBALBalance, noVeBALBalance } = useVebalUserData()
+
+  // FIXME: [JUANJO] everything needs a number here, but we should work with bigint
```
Comment (agorer) [inline packages/lib/modules/vebal/vote/Votes/MyVotes/MyVotes.tsx:44]: Wherever numbers are used for calculation we need to change to use either bigint or bignumber, but we should probably have some tests around to refactor this.

File: packages/lib/modules/vebal/cross-chain/CrossChainBoost.tsx [hunk 2]
```diff
@@ -42,7 +43,7 @@ export function CrossChainBoost() {
 
   const [syncIsOpen, setSyncIsOpen] = useState(false)
 
-  const { myVebalBalance } = useVebalUserData()
+  const { veBALBalance } = useVebalUserData()
```
Comment (agualis) [inline packages/lib/modules/vebal/cross-chain/CrossChainBoost.tsx:46]: We are calling `formatUnits(veBALBalance, 18)` in many places. Why not exposing a new `veBalBalanceUnits` from `useVebalUserData`?

**Review by agualis — CHANGES_REQUESTED** [review]

File: packages/lib/modules/vebal/cross-chain/CrossChainBoost.tsx (hunk 2 above)
Comment (agorer) [reply packages/lib/modules/vebal/cross-chain/CrossChainBoost.tsx:46]: Will probably first wait till we change all the calculations to use the raw bigint value, and then check if it is used just for formatting. Probably a formatting function without side effects?

File: packages/lib/modules/vebal/VebalStats/UserVebalStatsValues.tsx [hunk 3]
```diff
@@ -22,17 +23,14 @@ export type VebalUserStatsValues = {
 export function UserVebalStatsValues() {
   const { isConnected } = useUserAccount()
   const lockData = useVebalLockData()
```
[the remark this answers is not in the document]
Comment (agorer) [reply packages/lib/modules/vebal/VebalStats/UserVebalStatsValues.tsx]: Was already being used, but made it more explicit.

**Review by agualis — APPROVED** [review]
